name: '$(major).$(minor).$(revision)'
pr: none
trigger:
  batch: true
  branches:
    include:
    - main
variables:
  npm_config_cache: $(Pipeline.Workspace)/.yarn
  major: 0
  minor: 0
  revision: $[counter(variables['minor'], 1)]
  appVersion: $(major).$(minor).$(revision)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    fetchDepth: 1
  - task: Npm@1
    displayName: Update Version
    inputs:
      command: custom
      verbose: false
      customCommand: version $(appVersion) --no-git-tag-version
  - task: Npm@1
    displayName: Run ESLint
    inputs:
      command: custom
      verbose: false
      customCommand: run lint:ci
  - task: ArchiveFiles@2
    displayName: Archive dist
    inputs:
      rootFolderOrFile: ./
      includeRootFolder: false
  - task: PublishPipelineArtifact@1
    displayName: Publish Pipeline Artifact
    inputs:
      path: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifactName: flatfile
